<script setup lang="ts">
</script>

<template>
  <div>
    SwitchDemo
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
    <p>switch文档</p>
  </div>
</template>

<style lang="scss" scoped>
</style>